all: 
	@pdflatex -shell-escape core_notes.tex
	@makeindex core_notes.idx

clean:
	@rm -f	core_notes.aux
	@rm -f	core_notes.bbl
	@rm -f	core_notes.idx
	@rm -f	core_notes.ilg
	@rm -f	core_notes.ind
	@rm -f	core_notes.lof
	@rm -f	core_notes.log
	@rm -f	core_notes.lot
	@rm -f	core_notes.out
	@rm -f	core_notes.pdf
	@rm -f	core_notes.toc
	@echo "Cleaned"
