all: 
	@pdflatex -shell-escape main.tex
	@makeindex main.idx

clean:
	rm -f	main.aux
	rm -f	main.bbl
	rm -f	main.idx
	rm -f	main.ilg
	rm -f	main.ind
	rm -f	main.lof
	rm -f	main.log
	rm -f	main.lot
	rm -f	main.out
	rm -f	main.pdf
	rm -f	main.toc

